print("::::::Enter Students bio data::::::")
name=input("Enter your name:")
age=input("Enter your age:")
roll=input("Enter your Roll number:")
uni=input("Enter your university name:")
matric=eval(input("Enter your Matric Percentage"))
inter=eval(input("Enter your Inter percetage:"))
print(f":::::::::Dear {name}! Here is your Student Data::::::::")
print(f"Your Full name is {name} \nYour Age is {age} \nYour Matric Percentage is {matric} % \nYour Inter percentage is {inter} % \nYour university name is {uni}")